language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-django22
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22


before_install:
  - export DJANGO_SETTINGS_MODULE=test.settings

install:
  - pip install -e .
  - pip install -r requirements.txt


script:
  - tox
